brew "zsh-completions"
brew "zsh-autosuggestions"
brew "terminal-notifier"
brew "herdr"
brew "sleepwatcher"
brew "yusukebe/tap/ax"
brew "can1357/tap/omp"
brew "ollama"
brew "shellcheck"
brew "shfmt"
brew "actionlint"
brew "ast-grep"
brew "hunk"
brew "ripgrep"
brew "fd"
brew "jq"
brew "gnu-sed"
brew "gawk"
brew "coreutils"
brew "sonar-scanner"
brew "typescript-language-server"
cask "azookey"
cask "1password"
cask "1password-cli@beta"
cask "google-chrome"
cask "google-japanese-ime"
cask "notion"
cask "notion-calendar"
cask "orbstack"
cask "phpstorm"
cask "warp"
cask "kiro-cli"
cask "alt-tab"
cask "raycast"
cask "slack"
cask "avast-security"
cask "brave-browser"
cask "caldigit-docking-utility"
cask "claude"
cask "claude-code@latest"
cask "sonarqube-cli"
cask "clion"
cask "codex"
cask "codex-app"
cask "datagrip"
cask "discord"
cask "dotnet-sdk"
cask "ghostty"
cask "goland"
cask "google-drive"
cask "google-gemini"
cask "hyper"
cask "intellij-idea"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "neat"
cask "nosql-workbench"
cask "obsidian"
cask "onedrive"
cask "onlyoffice"
cask "raindropio"
cask "soundsource"
cask "stablyai/orca/orca"
cask "superwhisper"
cask "switchresx"
cask "tableplus"
cask "telegram"
cask "visual-studio-code"
cask "whatsapp"
cask "zoom"
cask "camo-studio"
cask "obs"
cask "microsoft-teams"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-word"
cask "grok-build"
mas "AudioSwitcher", id: 561712678
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "MARKETSPEED", id: 946680495
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
