tap "cirruslabs/cli"
tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "siketyan/mozc"
brew "bat"
brew "curl"
brew "flyctl"
brew "gh"
brew "git"
brew "hyperfine"
brew "mas"
brew "pict"
brew "tree"
brew "yq"
cask "1password"
cask "1password-cli"
cask "alt-tab"
cask "arc"
cask "avast-security"
cask "brave-browser"
cask "caldigit-docking-utility"
cask "clion"
cask "datagrip"
cask "deepl"
cask "discord"
cask "ghostty"
cask "goland"
cask "google-chrome"
cask "google-drive"
cask "hyper"
cask "intellij-idea"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "kobo"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-teams"
cask "microsoft-word"
cask "mozc"
cask "mozc@pre"
cask "neat"
cask "notion"
cask "onedrive"
cask "orbstack"
cask "phpstorm"
cask "raindropio"
cask "raycast"
cask "skype"
cask "slack"
cask "soundsource"
cask "switchresx"
cask "tableplus"
cask "telegram"
cask "utm"
cask "visual-studio-code"
cask "warp"
cask "whatsapp"
cask "zoom"
mas "AudioSwitcher", id: 561712678
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "MARKETSPEED", id: 946680495
mas "Messenger", id: 1480068668
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Unsplash Wallpapers", id: 1284863847
mas "Xcode", id: 497799835