#!/bin/bash

if [ "$(uname)" != "Darwin" ] ; then
	echo "Must be Mac OS. Unknown OS is detected"
	exit 1
fi

# Disable spotlight
sudo mdutil -a -i off
sudo chmod 0 /System/Library/CoreServices/Search.bundle/Contents/MacOS/Search

# brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# devbox
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
curl -fsSL https://get.jetify.com/devbox | bash